name: Build 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install pip deps
        run: |
          uv venv --python 3.11
          uv pip install mkdocs-material mkdocstrings[python] griffe-pydantic
          uv pip install git+https://github.com/Jaded-Encoding-Thaumaturgy/muxtools.git
          uv pip install --no-deps git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-muxtools.git git+https://github.com/Vodes/vodesfunc.git
      - name: Build and deploy site
        run: uv run mkdocs gh-deploy --force