name: Build 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prep Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pip deps
        run: |
          python -m pip install --user mkdocs-material mkdocstrings[python]
          python -m pip install --user git+https://github.com/Jaded-Encoding-Thaumaturgy/muxtools.git
          python -m pip install --no-deps --user git+https://github.com/Jaded-Encoding-Thaumaturgy/vs-muxtools.git
      - name: Build and deploy site
        run: mkdocs gh-deploy --force